import { ArrowLeft, BarChart3, CheckCircle2, ChevronRight, FileText, FolderOpen, Home, LogOut, MessageSquare, ShieldCheck, Ticket, UserRound, Workflow } from 'lucide-react';
import { DEMO_MODE_LABEL, demoActivity, demoClient, demoWorkItems } from '../lib/demoData';

const portalLinks = [
  { label: 'Dashboard', slug: 'dashboard', icon: Home }, { label: 'AR overview', slug: 'ar', icon: Workflow },
  { label: 'Denials', slug: 'denials', icon: FileText }, { label: 'Claims & billing', slug: 'claims', icon: BarChart3 }, { label: 'Verification', slug: 'verification', icon: ShieldCheck }, { label: 'Prior authorization', slug: 'authorizations', icon: Workflow },
  { label: 'Reports', slug: 'reports', icon: BarChart3 }, { label: 'Documents', slug: 'documents', icon: FolderOpen },
  { label: 'Requests', slug: 'requests', icon: Ticket }, { label: 'Messages', slug: 'messages', icon: MessageSquare }, { label: 'Profile', slug: 'profile', icon: UserRound },
];

function PortalShell({ children, active }: { children: React.ReactNode; active: string }) {
  return <div className="min-h-screen bg-slate-50 text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-200 bg-white lg:block"><div className="flex h-20 items-center gap-3 border-b border-slate-100 px-6"><div className="grid h-10 w-10 place-items-center rounded-xl bg-navy-900 text-white"><ShieldCheck className="h-5 w-5" /></div><div><p className="font-bold text-navy-900">Optimus RCM</p><p className="text-xs text-slate-500">Client portal</p></div></div><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-semibold uppercase tracking-wide text-brand-600">{DEMO_MODE_LABEL}</p><p className="mt-1 text-sm font-semibold text-navy-900">{demoClient.name}</p></div><nav className="space-y-1 p-4">{portalLinks.map(({ label, slug, icon: Icon }) => <a key={slug} href={`/client/${slug}`} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active === slug ? 'bg-brand-50 text-brand-700' : 'text-slate-600 hover:bg-slate-50'}`}><Icon className="h-4 w-4" />{label}</a>)}</nav></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur lg:px-8"><div><p className="text-sm font-semibold text-navy-900">{demoClient.name}</p><p className="text-xs text-slate-500">Client visibility workspace</p></div><div className="flex items-center gap-3"><a href="/" className="hidden items-center gap-2 text-sm text-slate-500 hover:text-slate-900 sm:flex"><ArrowLeft className="h-4 w-4" />Public site</a><a href="/client/login" className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100"><LogOut className="h-4 w-4" />Exit demo</a></div></header><main className="mx-auto max-w-7xl p-5 lg:p-8">{children}</main></div></div>;
}

function Title({ title, text }: { title: string; text: string }) { return <div className="mb-8"><p className="text-sm font-semibold text-brand-600">{DEMO_MODE_LABEL}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-navy-900">{title}</h1><p className="mt-2 max-w-2xl text-slate-500">{text}</p></div>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold text-navy-900">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>; }

function Dashboard() { return <PortalShell active="dashboard"><Title title="Your RCM overview" text="A clear view of the work Optimus is tracking for your practice. This portal preview uses fictional demonstration data." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Outstanding AR" value="$6,060" note="Demo balance across open items" /><Metric label="Open denials" value="2" note="Items moving through review" /><Metric label="Claims in progress" value="1" note="Demo billing queue" /><Metric label="Open requests" value={`${demoClient.openRequests}`} note="Questions for the Optimus team" /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent activity</h2><a href="/client/messages" className="text-sm font-semibold text-brand-700">View messages</a></div><div className="mt-5 space-y-4">{demoActivity.map((entry) => <div key={entry.title} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" /><div><p className="text-sm font-medium">{entry.title}</p><p className="mt-1 text-xs text-slate-500">{entry.detail} · {entry.time}</p></div></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Active services</h2><div className="mt-5 space-y-3">{demoClient.services.map((service) => <div key={service} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{service}</div>)}</div></section></div></PortalShell>; }

function Ar() { const items = demoWorkItems.filter((item) => item.module === 'AR Calling'); return <PortalShell active="ar"><Title title="Accounts receivable" text="Client-safe visibility into outstanding work and follow-up progress." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total outstanding" value="$6,060" note="Fictional demo balance" /><Metric label="91-120 days" value="$4,820" note="Requires focused follow-up" /><Metric label="Follow-up today" value="1" note="Optimus team action" /></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">AR items</h2></div><div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-800">{item.reference}</p><p className="mt-1 text-sm text-slate-500">{item.payer} · {item.followUp}</p></div><div className="flex items-center gap-4"><span className="text-sm font-bold text-navy-900">{item.amount}</span><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{item.status}</span></div></div>)}</div></section></PortalShell>; }

function Denials() { const items = demoWorkItems.filter((item) => item.module === 'Denials'); return <PortalShell active="denials"><Title title="Denial resolution" text="Track denial reasons and resolution progress without internal notes or staff assignments." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Open denials" value="2" note="Fictional demo records" /><Metric label="Appeal required" value="1" note="Documentation requested" /><Metric label="Amount in review" value="$1,275" note="Demo amount" /></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Denial queue</h2></div>{items.map((item) => <div key={item.id} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.reference}</p><p className="mt-1 text-sm text-slate-500">{item.detail}</p></div><div className="flex items-center gap-4"><span className="font-bold">{item.amount}</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">{item.status}</span></div></div>)}</section></PortalShell>; }

function Claims() { const item = demoWorkItems.find((workItem) => workItem.module === 'Billing'); return <PortalShell active="claims"><Title title="Claims & billing" text="Client-facing claim status and billing visibility for the fictional Summit Family Health account." /><div className="grid gap-4 sm:grid-cols-3"><Metric label="Ready to submit" value="1" note="Demo claim" /><Metric label="In progress" value="1" note="Demo status" /><Metric label="Payment posting" value="1" note="Demo exception queue" /></div><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Claim activity</h2><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="font-semibold">{item?.reference}</p><p className="mt-1 text-sm text-slate-500">{item?.payer} · {item?.detail}</p><span className="mt-3 inline-flex rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{item?.status}</span></div></div></PortalShell>; }

function Reports() { return <PortalShell active="reports"><Title title="Reports" text="Presentation-ready sample reports for the client portal." /><div className="grid gap-5 md:grid-cols-2">{['AR aging summary', 'Denial summary', 'Claims activity', 'Collections overview'].map((report) => <div key={report} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><BarChart3 className="h-5 w-5 text-brand-600" /><h2 className="mt-4 font-semibold">{report}</h2><p className="mt-2 text-sm text-slate-500">Sample report prepared for demonstration.</p><button type="button" className="mt-5 text-sm font-semibold text-brand-700">View sample report <ChevronRight className="inline h-4 w-4" /></button></div>)}</div></PortalShell>; }

function SimplePage({ page }: { page: string }) { const titles: Record<string, string> = { documents: 'Documents', requests: 'Requests', messages: 'Messages', profile: 'Profile', verification: 'Insurance verification', authorizations: 'Prior authorization' }; const descriptions: Record<string, string> = { documents: 'A secure document center prepared for future Supabase Storage integration.', requests: 'Submit and track questions for the Optimus team.', messages: 'A communication center foundation for operational updates.', profile: 'Practice and account information for the client portal.', verification: 'Client-safe visibility into coverage verification progress.', authorizations: 'Client-safe visibility into authorization requests and expiration dates.' }; return <PortalShell active={page}><Title title={titles[page]} text={descriptions[page]} /><div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="flex items-start gap-4"><CheckCircle2 className="mt-0.5 h-6 w-6 shrink-0 text-emerald-600" /><div><h2 className="font-semibold">Demo foundation ready</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">This area is intentionally limited to client-safe presentation content. Production records, file downloads, tickets, and messaging require their own Supabase tables and policies.</p></div></div></div></PortalShell>; }

export default function ClientPortal({ page }: { page: string }) { if (page === 'dashboard') return <Dashboard />; if (page === 'ar') return <Ar />; if (page === 'denials') return <Denials />; if (page === 'claims') return <Claims />; if (page === 'reports') return <Reports />; return <SimplePage page={page} />; }
